### ISSUE TITLE
Bug, this assumes every slice argument is the last slice

### ISSUE THREAD

**Issue by agentydragon** [infinytum/reactive#4]
https://github.com/infinytum/reactive/blob/c12d8413dd3d7e266111a1bdad36c396f4385c42/subject.go#L64

**Comment by nilathedragon** [comment]
The issue here was a broad if-statement which assumed that 

1) All slices are variadic arguments
2) Assumed that a slice as a variadic means the last argument

This has been fixed by adjusting the if statement to the following

1) Check function if it is variadic
2) check if the current parameter is a slice
3) make sure we are on the last available param, which to my knowledge must be the variadic.
